version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    # ports:
    #   - "3000-3001:3000"
    environment:
      - PORT=3000
    # depends_on:
    #   - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes: # A separate declaration for named volumes need to be provided as this service can be used with other containers (https://www.youtube.com/watch?v=9zUHg7xjIqQ @ 1:57:00)
  mongo-db:
